### ISSUE TITLE
Questions regarding custom tokens

### ISSUE THREAD

**Issue by fotoflo** [lowfront/next-auth-firestore-adapter-example#1]
Hello, thank you for putting this important example together!

my app will use tokens from two different providers - google and github to make different calls. 

With google I will initially log the user in with their Profile scope and later I will upgrade their scope to get the API we need access to.

Can you explain a little how this should work?

After running your example Im getting an error that the user cannot access the data - if i open up the access rules, then they can.

I've spent a couple of days on this already TBH and still cant figure out how to get the tokens to the user or how to auth the user to write to the database with the rules locked down properly.

thank you!!

**Comment by fronterior** [comment]
Hi, Can you pass me an example that doesn't work? 

Scope is supposed to be set through `NextAuth`'s provider, but I'm not sure if `NextAuth` supports scope expansion.

This example shows how to properly separate access rights when using `NextAuth` and `Firebase`.

I think you can only do what you want if `NextAuth` supports the feature.

**Comment by fotoflo** [comment]
Hi there! I managed to get scope expansion to work... but token refresh is not implemented i don't think?
